-- 코드를 입력하세요
SELECT C.CAR_ID, C.CAR_TYPE, ROUND((((100 -P.DISCOUNT_RATE) / 100) * C.DAILY_FEE) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P USING(CAR_TYPE)
WHERE C.CAR_TYPE IN ('세단','SUV') AND P.DURATION_TYPE = '30일 이상'
AND C.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01')
HAVING FEE BETWEEN 500000 AND 2000000
ORDER BY 3 DESC, 2, 1 DESC