-- 코드를 입력하세요
SELECT FOOD_TYPE, 
(SELECT REST_ID 
 FROM REST_INFO 
 WHERE FOOD_TYPE = R.FOOD_TYPE 
 ORDER BY FAVORITES DESC 
 LIMIT 1) AS REST_ID, 
 (SELECT REST_NAME 
 FROM REST_INFO 
 WHERE FOOD_TYPE = R.FOOD_TYPE 
 ORDER BY FAVORITES DESC 
 LIMIT 1) AS REST_NAME,
(SELECT FAVORITES 
 FROM REST_INFO 
 WHERE FOOD_TYPE = R.FOOD_TYPE 
 ORDER BY FAVORITES DESC 
 LIMIT 1) AS FAVORITES
FROM REST_INFO R
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC