-- 코드를 입력하세요
WITH RECURSIVE NUM(HOUR) AS(
SELECT 0
UNION ALL
SELECT HOUR+1 FROM NUM WHERE HOUR<23
)

SELECT A.HOUR, 
CASE WHEN B.CNT IS NULL THEN 0
ELSE B.CNT END AS COUNT
FROM NUM A
LEFT JOIN (SELECT HOUR(DATETIME) AS H, COUNT(ANIMAL_ID) AS CNT
          FROM ANIMAL_OUTS O
          GROUP BY 1) AS B ON A.HOUR = B.H