-- 코드를 입력하세요
SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE,'%Y-%m-%d') 'REVIEW _DATE'
FROM REST_REVIEW R
LEFT JOIN MEMBER_PROFILE M USING(MEMBER_ID)
WHERE M.MEMBER_ID = (
SELECT MEMBER_ID
FROM REST_REVIEW
GROUP BY 1
ORDER BY COUNT(REVIEW_ID) DESC
LIMIT 1)
ORDER BY 3,2

